### ISSUE TITLE
not able to insall all module

### ISSUE THREAD

**Issue by margish100** [meteoswiss-mdr/pyrad#43]
I have install the pyrad model using conda but when i run the script that time i given the error
1- can you give me proper setup file
2- readme file - https://github.com/meteoswiss-mdr/pyrad i am following this link but i am not able install packages
3 - https://github.com/meteoswiss-mdr/pyrad/blob/master/doc/pyrad_user_manual.pdf
   above link i am following not able to install all packages
Please can you give me one proper setup document

**Comment by margish100** [comment]
@jfigui 
@wolfidan 
@fvanden 
@meteoswiss-mdr

**Comment by margish100** [comment]
/Desktop/pyrad/pyrad/src/pyrad_proc/pyrad/EGG-INFO/scripts$ python3.6 main_process_data_rt.py 
Traceback (most recent call last):
  File "main_process_data_rt.py", line 47, in <module>
    from pyrad.flow.flow_control import main_rt as pyrad_main
ModuleNotFoundError: No module named 'pyrad.flow'

**Comment by wolfidan** [comment]
Dear @margish100 ,

Sorry but this repo is deprecated as indicated on the main page and not maintained anymore.
Did you use the version from the new repo? https://github.com/MeteoSwiss/pyrad/
Thanks

**Comment by margish100** [comment]
hi @wolfidan,
yes i have using this new repo, but i have facing the same issue.

/Desktop/pyrad/pyrad/src/pyart/examples/plotting$ python3 plot_ppi_mdv.py 


Traceback (most recent call last):
  File "plot_ppi_mdv.py", line 17, in <module>
    from pyart.testing import get_test_data
ImportError: cannot import name 'get_test_data'
